import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home() {
  <Head>
    <title>Pokemon App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  return (
    <>
      <main className={styles.landing_page}>
        <div className={styles.container_landing_page}>
          <div className={styles.hero_image_wrapper}>
            <span className={styles.pokemon}></span>
          </div>
          <>
            <div className={styles.nav}>
              <span className={styles.ctn_logo}>
                <Image
                  src="/images/logo.svg"
                  alt="@brandorodriguez"
                  width={140}
                  height={51}
                />
              </span>
              <span className={styles.btn1}>
                <Image src="/images/github.svg" alt="@brandorodriguez" width={28} height={28} />
              </span>
            </div>
          </>
          <div className={styles.bg_title}>
            <h2 className={styles.title}>Pikachu</h2>
          </div>
          <div className={styles.content_wrapper}>
            <span className={styles.badge}>
              <span>new project</span>
              Pokemon App
            </span>
            <h3 className={styles.h3}>Les´t Go, Pokemons.</h3>
            <p className={styles.p}>
              All the Pokémon data you'll ever need in one place, easily
              accessible through a modern PokeApp.
            </p>
            <span className={styles.btn} >
              Explore now.
            </span>
          </div>
        </div>
      </main>
    </>
  )
}
